### ISSUE TITLE
add unsafe ops from array from Data.Array and Data.Array.IArray

### ISSUE THREAD

**Issue by andrewufrank** [ndmitchell/safe#13]
these two packages throw errors for out of bounds at the indexing function `!` and for `accum`.
i tried to write functions to catch these errors with a safe function, added to my code. i have the impression that i have to copy too much from the Utils module and get a name clash for .^.

my current code for a functin `atA2Note`, which is adapted from `atNote`: 

```
atA2Note :: (Show pos, Ix pos) => String -> Array pos a -> pos  -> a
atA2Note note = fromNoteEither note "atA2Note" .^+ atA2

atA2 :: (Show pos, Ix pos) =>  Array pos a -> pos -> Either String a
atA2 xs o | inRange (bounds xs) o  = Right $ xs ! o  
    | otherwise = 
            Left . unwords $ ["index out of bounds, index=", show o,
                        "bounds", show (bounds xs)]

(.^+) :: (b -> c) -> (a1 -> a2 -> b) -> a1 -> a2 -> c
(.^+) f g x1 x2 = f (g x1 x2)

fromNoteEither = fromNoteEitherModule "Safe"

fromNoteEitherModule :: String -> String -> String -> Either String a -> a
fromNoteEitherModule modu note func = either (error . msg) id
    where msg ex = modu ++ "." ++ func ++ " " ++ ex ++ (if null note then "" else ", " ++ note)
```

i do not understand enough of safe to see the proper way to integrate this code. 

perhaps one could export from safe the necessary functions to extend it and write a short description how to do this - there are likely more packages which would benefit from safe.

**Comment by ndmitchell** [comment]
Ignoring the implementation concerns, I don't think adding array functions is worthwhile for three reasons:

* People tend to use Data.Vector instead of Array, since the performance of Array is typically terrible. Vector already has things like `!?` which are Maybe wrapped index versions.
* The safe library currently only depends on base, not the array library, so it would increase the dependencies for a feature I suspect few would use.
* When it comes to array, the term "safe" is already overloaded to mean with bounds checks and without, so overloading it to mean exceptions and non-exceptions is likely to get confusing.

Does that make sense?

**Comment by andrewufrank** [comment]
sorry for not being precise. my question was not about adding safe functions to `Array `but to export from `Safe` the functions necessary for others to build similar safe wrappers for other functions in other packages themselves. i tried to do this and was not successful, running in a name clash for `.^.` ; perhaps you could add instructions showing how to use the basic code in `Safe` to make other functions in other packages safe. 

thank you for pointing to `Data.Vector` which i will consider to replace `Array`; i had some other considerations to prefer `Array,` but perhaps these consideratins were not justified.
