### ISSUE TITLE
Create a function to get init/last in one pass ?

### ISSUE THREAD

**Issue by nineonine** [ndmitchell/safe#23]
I had a case where I had to use  `lastDef` and `initDef`. Would it be possible to have a function that computes all the necessary values in one pass?

**Comment by ndmitchell** [comment]
There is [unsnoc from extra](https://hackage.haskell.org/package/extra-1.6.8/docs/Data-List-Extra.html#v:unsnoc), which returns the pair and a `Nothing` for the empty list:

```haskell
unsnoc :: [a] -> Maybe ([a], a)
```

Perhaps you could use that composed with `fromMaybe`? I'm not keen on adding the fused version to `safe`, because `initLast` isn't in the base library, and that would be the function it was "making safe".

**Comment by nineonine** [comment]
Yeah, this should work. Closing this.
Thanks!
