### ISSUE TITLE
Haddock documentation

### ISSUE THREAD

**Issue by myroslambda** [ndmitchell/safe#31]
I saw that [many functions](https://hackage.haskell.org/package/safe-0.3.19/docs/Safe-Exact.html#g:2) lack haddock documentation. Is this on purpose, meaning that you consider them self-explanatory, or would you welcome PRs that complete that missing documentation?

**Comment by ndmitchell** [comment]
Most functions are a formula over some existing name, so I put the docs for all of them at the top of the module, and then just list the functions. Otherwise its much  harder to see which functions are available. So yes, it was on purpose - do you think it would be useful? And that use would be greater than the cost of not being able to scan the functions in the module so easily?

**Comment by myroslambda** [comment]
If it's on purpose then perhaps it's best to leave it at is. Normally I would propose to link to the original functions in the same module (for example to at least link to the documentation for `take`, `drop`, `split`) but these are well known functions too.
